# Generated by Django 5.2.3 on 2025-06-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
