# Generated by Django 5.2.3 on 2025-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_service', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
